### ISSUE TITLE
[FEATURE] clickable link in the personal message from contact list

### ISSUE THREAD

**Issue by KinG-InFeT** [emesene/emesene#1000]
emesene1 as in, you could add a function that in the contact list, clicking the right mouse button on the contact, if it in his personal message has 1 or more links, they are recognized and that came out a list of links on them and click to open in the browser.

**Comment by Sbte** [comment]
I think we rejected this before. #984 should be sufficient. You can also copy paste stuff from the conversation window (right click on the header). 

If you still want this, please implement it as a plugin. Since you have the skills to get your site reported as harmful you should also be able to make such a plugin ;)

**Comment by KinG-InFeT** [comment]
well I would have been something much more simple and convenient as emesene1.
