### ISSUE TITLE
Notification issues

### ISSUE THREAD

**Issue by Pieeeeeee** [emesene/emesene#1022]
I'm new here, so sorry if I do anything not right.

I just installed Emesene 2.12.1 on my Windows 7 64 bit. There are multiple things I'd like to report, I'll do the notifications here.

First problem: I have a dual screen, and the notification pops up at the second screen, while it should popup at the mainscreen. Live Messenger does this correct, also aMSN. Haven't tried other clients.

Second: I think the configuration options are incomplete. Normally I don't want a notification when I recieve a new message, UNLESS it's the first message of a new conversation. In Emesene one can only select to always show it or never. The sounds do have that option though.

Third: there's no option to show "when a contact is typing" in the chatwindow, like in WLM, only in a popup window. I find that a quiet anoying way of knowing someone is typing something.

Fourth: in Messenger Plus, a notification of a contact going offline is showed only when there's a conversation window opened of that contact. In Emesene it's always showed, even when you weren't talking to that person.

**Comment by Stiveknx** [comment]
About Third, in status icon (online, offline), when it's gray and have 3 dots the user it's typing the message ...

**Comment by pepeleproso** [comment]
3 -  there's a plugin that show a message like WLM do

**Comment by c10ud** [comment]
1. we don't have multiple screens so we don't know how to even handle this
2. you should receive a notification when the window doesn't have the focus, if that's not the case please open a bug about it -- otherwise it's just a "i want this" versus "we did that" and i don't think it will change unless patches are provided
3. see sbte's comment
4. patches welcome, we're not msn+ though, we don't have encrypted logs nor audio clips, etc. ;)
