### ISSUE TITLE
Ubuntu 12.04 and emesene dependency

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1071]
While trying to install emesene in ubuntu center programs, seeks to remove the following packages:
- libfarstream-0.1-0
- libpurple0

**Comment by Sbte** [comment]
@dfiloni

**Comment by c10ud** [comment]
i think you should open an bug for the emesene package in precise so they can sort this out before universe freeze

**Comment by dfiloni** [comment]
This is not and emesene package bug, it's a dependencies one.

**Comment by trism** [comment]
I have raised https://bugs.launchpad.net/ubuntu/+source/emesene/+bug/956422 on launchpad. The issue was that farsight2 was renamed to farstream upstream. The symbols are the same, but there was a mass renaming of farsight to farstream. I attached a branch that should fix the package, and this will probably need to be fixed in the emesene git eventually.

**Comment by zipatei** [comment]
fixed a733f586aae93221de22e728c29cd51693bf243b
