### ISSUE TITLE
[papylib] leave multichat when closing the chat tab(window)

### ISSUE THREAD

**Issue by c10ud** [emesene/emesene#11]
as title says :)

**Comment by cando** [comment]
here it works...when i close the tab i also leave the multichat...
I've tried from emesene2 to emesene1 and when in emesene2 i close the multichat window in emesene1 my contact disappears....The problem is that in emesene1 the title of the conversation window remain "Group Chat"...

it should work because when i close the window i've put a switchboard.leave() papylib call....

**Comment by c10ud** [comment]
oh ok..i'll test more maybe i didn't check more than watching emesene1 window :)

**Comment by cando** [comment]
ok...let me know!

**Comment by cando** [comment]
any update on this issue???

**Comment by c10ud** [comment]
yes, just tried and it works, it was another emesene that mislead me because of its nasty sounds lol!
