### ISSUE TITLE
GTK+3/PyGObject porting?

### ISSUE THREAD

**Issue by Mastergatto** [emesene/emesene#1103]
While GNOME 3.4 has just been released, I've noticed that emesene is still written in PyGTK (python binding of gtk+2 libraries).
Considering that PyGTK has been deprecated (it will be dropped on the distros too) in favour of PyGObject, and emesene's theme is a bit inconsistent with the GTK+3 desktop; I suggest you to consider the porting to PyGobject, or at least activate the layer compatibility with PyGTK. See here for more info: https://live.gnome.org/PyGObject/IntrospectionPorting

**Comment by c10ud** [comment]
I thought about this.

We could do a painful transition to gtk3 which atm noone wants to do it (or has time to),

or, or,

we could just fix the Qt4 ui (possibly removing the 4, since Qt is version 5 soon and using pyside instead of pyqt since it seems the standard (?)) and ditch gtk completely, leaving it in the tree or in another branch just for the history.

pros:
- packagers' life would be easier (e.g. windows, osx)
- Qt integrates with the OS easily
- we already have an almost working Qt ui
- we learn Qt+python (i know it with c++ already)

cons:
- you cannot write anymore that emesene is a pygtk im
- no idea

ideas?
@Sbte @pepeleproso

![true story](http://i.imgur.com/lQLxY.jpg)

**Comment by KinG-InFeT** [comment]
surely the QT libraries are much more powerful than GTK ... in my opinion would make a port to QT new life to emesene.

**Comment by ricsipontaz** [comment]
+1 for Qt. :)

**Comment by Sbte** [comment]
Though porting emesene to Qt is a fun project, none of the current devs has time to do it (it will take months), so porting to gtk3 instead is most likely to happen. +1ing doesn't help unless you start coding yourself ;)

**Comment by Mastergatto** [comment]
It isn't true that transition to GTK+3 would be painful and hard as stated before, because there are only few differences between PyGTK and PyGObject, mainly the renaming of functions, and it can be done with a script that can be found in the page I have linked above. Of course, you can't just rename all the functions using the script, as there may be some changes in some of them, so you'd have to look for errors as well, but it still wouldn't be as hard as writing it from scratches.

Thanks to the new emesene's architeture (gui and core are separated), one can make other guis easily without touching the core, so I can't see why the transition to Qt could bring improvements to emesene's development, although a Qt gui could be a nice alternative.
Imho, you should keep GTK+ gui as the default one, because it is widespread thanks to Ubuntu. Also emesene is commonly known as a client MSN written in GTK+, so you'd need to "rebrand" it.

**Comment by c10ud** [comment]
i'm eager to pull in your gtk3ui branch then, since it's that easy :)

**Comment by pepeleproso** [comment]
We decide to port to gtk3, and to improve little by little the qt ui.

Porting to gtk3 isn't an easy task, we use many lowlevel gtk stuff, like gtkstyle, gdk colors, gdk drawing apis. There's also the new draw and sizing methods of gtk3 for our custom widgets.
We also use pango and cairo stuff, which is broken on GI, so we need to rewrite those parts someway. Also gtk3 don't work on windows and macos, so porting means we can't support them.

Seeing that this bug is causing more problems than solutions I'll close this
