### ISSUE TITLE
Single Window

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1260]
Single instance is awesome but...

1) I open a chat window. How can I just close the window?

2) Open a chat window. I click CTRL + W. Open emesene in MeMenu. Appears the contact list and an empty space on the right side.

**Comment by c10ud** [comment]
1) you can't unless you middle click it but that closes the whole emesene - we can easily show the X tab button haxing here https://github.com/emesene/emesene/blob/master/emesene/gui/gtkui/ConversationManager.py#L234 but that breaks the whole point of single window?

2) correct, no conversation is avail hence the empty space (?) skypetab-ng behaves the same way

**Comment by zipatei** [comment]
1) I think the best would be to put the x if possible.

2) I think we should correct, where we closed the window, restore the contact list.

**Comment by c10ud** [comment]
putting the x would to the same as ctrl+w or middle click though

as for restoring dimensions, that would either involve an insane amount of coding (because now width and height are the same as other options - multiple windows, tabbed windows - just...reused) or keeping it as it is (simpler)

same thing for closing only the conversation part since the quit/close callbacks are shared with the mainwindow: insane amount of coding for multiple (useless?) behaviour or leaving as it is

**Comment by zipatei** [comment]
But you can not do as the show / hide avatar?

**Comment by zipatei** [comment]
Already now take this opportunity to suggest something of the genus of the Opera. By double-clicking on the tab width, it returns to normal. Twice again, back to what it was.

**Comment by Sbte** [comment]
I mostly fixed the empty space thing I think. It's just not very clean yet. Same holds for closed conversations (single window or not). It's broken.

**Comment by zipatei** [comment]
Suggestion (example opera browser):

1) Default ( http://imageshack.us/photo/my-images/269/operag.png/ )
2) Two clicks
3) Result ( http://imageshack.us/photo/my-images/818/opera1.png/ )
4) Two clicks
5) Default ( http://imageshack.us/photo/my-images/269/operag.png/ )

Idea to Emesene

1) Emesene default (or save last size) : http://imageshack.us/photo/my-images/51/emesenej.png/
2) two clicks
3) result: http://imageshack.us/photo/my-images/831/emesene1.png/
4) two clicks
5)  Emesene default (or save last size) : http://imageshack.us/photo/my-images/51/emesenej.png/

**Comment by zipatei** [comment]
@Sbte After your commit, always i open a conversation window, conversation was hide.

**Comment by zipatei** [comment]
Empty space: http://imageshack.us/photo/my-images/850/emptyb.png/

reproduce:

1) open conversation
2) close conversation with ctrl + w
3) memenu - emesene

**Comment by zipatei** [comment]
Put close button just in single window:

ConversationManager:

```
def update_close_buttons(self):
    """
    Show or hide the close buttons on tab labels
    """
    if not self.session.config.b_single_window:
        show = self.get_n_pages() > 1 and self.session.config.b_close_button_on_tabs
        for conv_index in range(self.get_n_pages()):
            self.get_nth_page(conv_index).tab_label.close.set_visible(show)
```

**Comment by Stiveknx** [comment]
Damm, I loved this feature, awesome!

But, need some corections, like: 
1) If the window it's not maximized, if you open an conversation, you can't see, only after maximizing, could maximize automatically maybe?

2) If you press "esc",with only one conversation opened, the whole window closes (emsene contact list and conversation)

3) If you close the conversation, the title is still the same as the contact name, not just "Emesene".
Let's say: I don't have any conversations open, the title is "Emesene". I open a conversation with "Bill Gates", the title changes to "Bill Gates". I close the conversation with him (he asks money even for that), the title is still "Bill Gates", instead of emesene.

**Comment by Sbte** [comment]
The original two bugs are fixed, and this issue is becoming a mess. Please open new issues for any leftover bugs.

**Comment by zipatei** [comment]
Yes... thanks @Sbte
