### ISSUE TITLE
Cannot open contact window

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1262]
commit 229817268fd94743648579738cb120e0f0728f12

Uncheck single window option. In the main window, open a contact. There's nothing shown for conversation.

(12:00:41) e3.common.Signal:Signal handler (_on_contact_selected._on_contact_selected) error: 'NoneType' object has no attribute 'present'
(12:00:45) gui.base.ConversationManager:Looking for conversations with the same cid: .....
(12:00:45) gui.base.ConversationManager:No similar conversation was found
(12:00:45) gui.base.ConversationManager:Constructing a new conversation: ......
(12:00:45) gui.base.ConversationManager:Looking for conversations with the same cid: ......
(12:00:45) gui.base.ConversationManager:No similar conversation was found
(12:00:45) gui.base.ConversationManager:Returning a new conversation

**Comment by moneycat** [comment]
first seen at d9cc35fb15514333140c2a49abe7c14a11c9464b

**Comment by c10ud** [comment]
thing is i didn't account for switching behaviours at runtime because i was lazy and messing up with different stuff could lead to moar issues. for now the preferred behaviour is set/unset single window and reboot emesene but i'll see if i can fix this so it doesn't break so bad if you try circumventing my will :p if others are willing to fix it, patches welcome!

**Comment by moneycat** [comment]
This issue maybe related to #1269

**Comment by moneycat** [comment]
Close this because of #1269 and commit f5f06006d01359c3e1d75b43d5c69140d407ac0e
