### ISSUE TITLE
[single_window] Make conversations shown beside the contact list

### ISSUE THREAD

**Issue by moneycat** [emesene/emesene#1276]
The current layout will cut the menu, entry and status for users. Is there possible to make the conversations in single window mode beside the contact list?

I've made some change but not work for non-single-window mode. How to make it work, any suggestion?

f111e54940469b13d5a52e1f9bb733eec808b46d
13a800d3b40268c6881cf6dbd1ed197ab3ff142c

**Comment by c10ud** [comment]
well those commit basically move the hacks to MainWindow.py instead of Window.py (?) I don't understand what you're trying to fix here..isn't conversation already shown beside the contactlist?

**Comment by moneycat** [comment]
@c10ud The current version of single window will shown the conversations by split the whole window because the HPaned box packed content_main and content_conv. The area of user avatar, nick, message and the search area will be cut.

http://imageshack.us/photo/my-images/805/singlewindow.png/

Current version is the left side while the right side is my modified version.

**Comment by moneycat** [comment]
Now in my modified version, the non-single-window mode encounter a problem that there is no parent of the pop-p window. This will cause crash in ConversationManager that i add a hack to set its parent.

Although the crash dismiss but there's no attached conversation window in the opened new window. I want to ask for any suggestion to solve this problem. :)

**Comment by c10ud** [comment]
well that's a design choice, i wanted to do it like skypetab-ng. See http://keks-n.net/skypetab/

IMHO the user area doesn't need to be _that_ big because it leaves a lot of useless blank space...

As for general issues with modifying the code, as i said to lfottaviano when dev'ing this new feature, current gtk window implementations rely a lot on ugly get_parent() hacks so trying to mess with them brings real pain. I would reccomend leaving everything as it is.

**Comment by moneycat** [comment]
@c10ud OK. Thanks for reply. I'll try to fix this issue because it's a good time to understad the architecture of emesene.
