### ISSUE TITLE
[Feature Request - Contact info] Add IM client version

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#1399]
Kmess informs the client has available the contact uses.

wlm in a chat window notifies the contact is to speak by messenger on the web.

**Comment by moneycat** [comment]
We seems no enough information provided by _handle_MSG although we have the sender's uuid...

Any idea @c10ud ?

**Comment by c10ud** [comment]
the only way to implement this (tell the user: your friend is using pidgin, kmess, or whatever) is handle nonstandard messages like what pidgin (libpurple) does which is something -- adding nonstandard stuff to papyon -- i do not want to do.

as for the messenger on the web, etc. i don't remember a protocol way to distinguish that -- and i don't even know what that would be useful for since the goal is simple: chat with buddies -- i think that one possibility is checking the capabilities of a contact and knowing what gives what you can extract the client... but as i said this is only speculation

my take on this issue is, won't fix
