### ISSUE TITLE
avatar: remove cell_key_position functionality

### ISSUE THREAD

**Issue by pepeleproso** [emesene/emesene#1427]
We agreed on avatar centered (Bug #1401), so this option is always hardcoded as gtk.gdk.GRAVITY_CENTER and it only makes code hard for no reason.

**Comment by moneycat** [comment]
I've remove it and the avatar seems works correctly because we set its coords when drawing. I also remove the `translate_key_postion` function which just using once in `AvatarManager`.

The `key-position` properties is related to `cell_key_position`. I removed it but I've no idea what it is.

d461e2abe8ea4ee4fd1b625549a32f9ef8d399b7

**Comment by pepeleproso** [comment]
yes, that's exactly what I mean. Please push.
As for the key-position they are gobject properties for cell renderers use, but there are unused.
