### ISSUE TITLE
Searching through contact list limitation

### ISSUE THREAD

**Issue by Peque** [emesene/emesene#269]
Seems that if you have empty groups hidden and you try to search for a contact, the search engine will only seek for contacts in the current shown groups, not in empty (hidden) groups.

Perhaps the search engine works fine and it's just that the hidding rules are applied too to the search output (and the found contact is hidden too, as it's in an empty group).

**Comment by c10ud** [comment]
i test this grouping offline contacts and not choosing "show offline contacts". if i start searching a contacts, they appear in the results so i guess this works..?

**Comment by Sbte** [comment]
And what if you don't show offline contacts, don't group offline contacts, and don't show empty groups? Then it doesn't work and that's what this bug is about.

**Comment by c10ud** [comment]
it works also in that situation, which is what i use by default

**Comment by Sbte** [comment]
It doesn't if the contact is in a hidden group. At least not for me.

**Comment by c10ud** [comment]
if with hidden you mean collapsed then we're ok. but it surely matches hidden contacts in uncollapsed (and also, yes, hidden) groups..and it even would with collapsed ones, the thing is you have to uncollapse them in order to see the result. as a workaround when ctrl+f we could uncollapse every group

**Comment by Sbte** [comment]
That's already done. So uncollapsed groups are not the problem indeed.

The problem is that groups with only offline contacts are assumed as empty groups and those are hidden (if you disable 'show empty groups') and won't show up if you search through the contact list. So contacts in those groups won't be displayed.

Edit: With sort by group enabled.

**Comment by Peque** [comment]
I think Sbte knows what I meant, but perhaps I didn't explain myself well c10ud (my English is just OK).

If you set the option "Order by group" and only check "Sort by name" (don't check none of "Show..." or "Group offline contacts") and then you search for a contact that is not connected and that is in a group where nobody else is connected, then that contact wont be listed in your search (not even in a collapsed group...).

**Comment by c10ud** [comment]
ok, now i understood better the issue
