### ISSUE TITLE
Showing status in brackets is pointless with status icon present

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#386]
There is no point in displaying a contacts status in brackets when the status icon already displays the information. All it does is take up room that could be used to display more of the personal message.

Instead the written out status (Online, Offline, Away, ect) should be shown when hovering over a contact.

**Comment by c10ud** [comment]
you can modify the template you like in contact list by editing in Preferences-Nick format..the default is:
[$DISPLAY_NAME][$NL][$small][$ACCOUNT][$/small][$NL][$small][$BLOCKED]([$STATUS]) - [$MESSAGE][$/small]
in order to show what can be done..maybe we can change it to a nicer default (just like emesene1 had..?)

**Comment by ghost** [comment]
Yea, similar to what emesene1 had, but it still showed the status in brackets for everything except Online.

**Comment by marianoguerra** [comment]
On Tue, Apr 12, 2011 at 5:53 PM, syst3mfailur3
reply@reply.github.com
wrote:

> There is no point in displaying a contacts status in brackets when the status icon already displays the information. All it does is take up room that could be used to display more of the personal message.
> 
> Instead the written out status (Online, Offline, Away, ect) should be shown when hovering over a contact.

you can remove it in preferences, maybe the new default is not to show it?

**Comment by c10ud** [comment]
i changed the default template since it's not the first time people
ask about it, i think it's cleaner(?) it's really just a matter of
taste, but i think this new one is nice

2011/4/12 marianoguerra
reply@reply.github.com:

**Comment by Sbte** [comment]
Exactly what I was already using. I think it suits more people indeed.

**Comment by c10ud** [comment]
...just without the l33t "c10ud" color i guess! egocentrism ftw!

2011/4/12 Sbte reply@reply.github.com:

**Comment by ghost** [comment]
It looks much better now. Only 2 other things that could make it a bit better would be to capitalize the first letter of the status, and the replace the word "invisible" with "Offline". Only the person that sets there status to invisible knows there are invisible, to everyone else they are simply offline.

**Comment by c10ud** [comment]
i'm unsure if i should capitalize statuses, translators will hate
me..but i guess i'll do it in the end.

as for the invisible/offline thing, you're right. i had to change it
because of consistency with ubuntu's indicator-me that lets the user
change status to invisible and offline(=disconnecting). maybe choosing
a different translation for contactlist and contactmenu button would
be a good choice.

if you could open an issue with your last comment and my reply, it
would be great,so i don't forget about it

2011/4/12 syst3mfailur3
reply@reply.github.com:

**Comment by c10ud** [comment]
fixed the invisible/offline thing
fixed capitalization

**Comment by ghost** [comment]
Seeing as its fixed, should i still go a head and open an issue?

**Comment by c10ud** [comment]
nope :D
