### ISSUE TITLE
Away, Busy, Idle notifications

### ISSUE THREAD

**Issue by ammarabdulsalam** [emesene/emesene#432]
Hello,
When a contact sign in with busy or away status there no notification appear.
It'll be nice to implement this.

Regards

**Comment by Mystro256** [comment]
I would assume you are referring to adding the option to allow notification/sound events (new messages/online contact/etc.) while busy or away? or do you mean a warning of not being set to online when signing in?

**Comment by Sbte** [comment]
No, he means that if someone signs in with a status other than online, a sound is played, but no notification is displayed. Sounds like a bug.

**Comment by Mystro256** [comment]
Oh okay, sorry :P

**Comment by c10ud** [comment]
most likely an "if status == ONLINE" must be changed to "status != OFFLINE" somewhere in notification.py

**Comment by Sbte** [comment]
let me see

**Comment by Sbte** [comment]
Ok, if you do that, every status change shows a notification. Currently, if you change from 'not online' to online as status you also see a notification. It shouldn't be there. There should probably be a better way to check this. Especially since the notification sounds seem to do everything correctly.
