### ISSUE TITLE
Can't change background color of conversation box with Audium

### ISSUE THREAD

**Issue by astagi** [emesene/emesene#450]
Hi all,

I'll report here this request of feature I would implement... In multiple conversation history I would choose another color for messages send by other users... For example if conversation is between A, B and C, A and B have the same predefined colors ( yellow and green ) and C for example blue.
As a developer, I tried to change some html value to make some test with audium, changing also values in gui.gtkui.conversation.html,  but unsuccessfully ( I think that is a useless file, never referenced ) :( :( Nothing changes.. Only thing I can do it's to modify audium themes folders, AudiumTheme.py or maybe would work surrounding a message with a div..Audium themes have 4 colors but let you use only 2 color combination in css..Also seems to get colors from images, not from a value, so I think it's impossible to apply this feature in conversation with more than 4 users..

Just discussed in ML, but reporter again here to avoid forgetting ;)

Feature for 2.1

**Comment by c10ud** [comment]
how does adium handle that? anyone that ever used it?

**Comment by arielj** [comment]
We can change some border property to another color (so we don't have to change everything), do something like this:

after the format_incoming method, you get the html code, before using that, do something like:

<code>
htmlcode = htmlcode.replace('<table class="tableBubble" cellspacing="0" cellpadding="0">', \
'<table class="tableBubble" cellspacing="0" cellpadding="0" style="background-color:#FFCC00;border-radius:8px;padding:4px;color:#FFFFFF;-webkit-box-shadow:inset 0 0 6px #000000;">')
</code>

that will add a shadow colored border to the incoming bubble, you can change the color with the "background-color" value

I'm not sure where to put this code and you need to assign one color for every participant, but it's a start!

you can try it modifying line 8 of Content.html for the Incoming messages to:
<code>
<table class="tableBubble" cellspacing="0" cellpadding="0" style="background-color:#FFCC00;border-radius:8px;padding:4px;color:#FFFFFF;-webkit-box-shadow:inset 0 0 6px #000000;">
</code>

EDIT: damn github, it's eating my html tags x3!!!!!!!!

EDIT2: github eats my html tags, check this comment, with tags, here http://pastebin.com/hTZzrm7e

**Comment by astagi** [comment]
Wooops...html code has gone, but no problem I received it from email :) Thanks man this works ;) I'll work on this feature for 2.1... Regards

**Comment by c10ud** [comment]
try to see what adium does first! leave haxing stuff as the last option please

2011/4/26 4ndreaSt4gi
reply@reply.github.com:

**Comment by arielj** [comment]
the content file just sets a class for the table element and then defines all it's colors/layout/etc on the css file

we can only add extra styles to the elements, beacuse we can't edit the adium theme files (or we'll need to modify every theme by hand)

we can't even change it's class, because we wouldn't have that "new" class defiend on the css file

**Comment by astagi** [comment]
Yes c10ud we're just at the last option :) Adium css files offer only 2 combinations of colors, we need N combinations... Arielj replacing solution, as Mariano said in the newsletter, seems to be the only possible way... it remains a mystery why adium doesn't support a color for every user but only a combination... I'll work to implement a clean solution ;)

**Comment by arielj** [comment]
Maybe he meant that not all adium themes behaves the same way, ravenant doesn't have tables, only divs, with other classes and such things, no images, only css colors, etc...

We can't rely on modifying the html code, because it's not always the same.

We can, though, add a wrapper div element and put a border in that div?, it will look ugly (weird colored border :P), but I can't think of another option, all adium themes can be different

Other option is to use always the same adium theme for chat history (say Renkoo), but it's not nice to do that.

**Comment by astagi** [comment]
You're right... yes, the div wrapper is a good idea, alternatively we could force the font color in <span> tag, that seems to be common in every theme...
