### ISSUE TITLE
Connection issues

### ISSUE THREAD

**Issue by Devilz** [emesene/emesene#523]
I can't connect at all with emesene 2 , I'm having troubles with my internet so I'm running without my router and cable modem so I'm running my Ubuntu 11.04 using 3G stick using Sakis3G to connect the 3G stick because Ubuntu cannot connect it for some reason so Sakis3G is just a script which makes it work
I connect , I can connect with whatever software but emesene 2 I can't
Everything works but emesene 2 (emesene 1 works)
I click connect after a moment I get reconnecting in 29..(countdown)

I think the reason of this problem might be that Ubuntu itself isn't connecting to anything(the network indicator at top) isn't showing that is connected but I'm connected using that script so there is connect-ivy in Ubuntu but Ubuntu standard network indicator isn't showing that it's connected but IT'S connected other IRC programs , browsers , IM programs all work and even the old emesene but emesene doesn't

Thanks :)

**Comment by arielj** [comment]
Can you connect to other protocols? I mean, Gtalk or Facebook, if so, the problem is in papyon and not emesene it self

Also, can you run emesene from a terminal? maybe it shows some error too.

**Comment by c10ud** [comment]
nope, i just added a NetworkManager checker, if NetworkManager is available, otherwise we cannot detect when the network is down and disconnect papyon accordingly. Since @Devilz has NetworkManager but he doesn't use it, emesene  thinks the network is down.

workaround: in emesene/emesene.py line 178 write:
DBusNetworkChecker = None

then you'd better fix your NM, or kill the service :)
