### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by leandro0012** [emesene/emesene#528]
I am using emesene 2.1.1.4 and I always have to disable the sounds and the online/offline notifications because my settings are not being saved.

**Comment by yuetenshi** [comment]
Lo mismo pasa con ordenar los contactos por estado o grupo, la fuente de letra que se usa para enviar mensajes y las opciones de Options > Preferences...

**Comment by Mystro256** [comment]
Most configuration issues related to emesene that I've dealt with tend to be caused by a problem with the configuration file (not sure of the cause...). If so or , you can try purging the emesene configuration (just delete ~/.config/emesene2/config), re-open emesene and choose your settings again. Also make sure the configuration file is owned by you (not sure why it wouldn't be but doesn't hurt to check).

Saving settings seem to save just find for me and many others, thus there must be something else that is having an issue, not just a general bug. If deleting the config doesn't help, can you provide terminal output or some sort of scenario? Unfortunately, it's "not being saved" doesn't help a whole lot :/

**Comment by c10ud** [comment]
once you set the options, close emesene gracefully File-Quit, it will work
