### ISSUE TITLE
msn HTTP method : can't chat

### ISSUE THREAD

**Issue by EchoUSB** [emesene/emesene#555]
Using the HTTP method, I can log in and see who's online , but I can't send nor receive messages.

Here is the error when trying to send a message: 

[20:14:14 DEBUG papyon.transport] <<< XFR 12 SB 64.4.61.114:1863 CKI 1200068752.183101233.2571129 U messenger.msn.com 1
[20:14:14 INFO papyon.protocol.switchboard] New switchboard session 1200068752.183101233.2571129
[20:14:14 DEBUG papyon.transport] <-> Connecting to gateway.messenger.hotmail.com:80
[20:14:14 DEBUG papyon.transport] >>> USR 0 XXXXXXYYYYY@hotmail.com;{a23e4040-496f-4d9d-9709-38f88d2d29c8} 1200068752.183101233.2571129
[20:14:15 DEBUG papyon.transport] <-> Changing gateway to 64.4.61.114:80
[20:14:15 WARNING papyon.gnet.HTTP] Received response but wasn't waiting for one
[20:14:19 DEBUG papyon.transport] <<< 911 0
[20:14:19 ERROR papyon.protocol.switchboard] Notification got error :911 0
[20:14:24 ERROR papyon.gnet.HTTP] Received error code 400 (Bad Request) from 64.4.61.114:80
[20:14:24 INFO papyon.protocol.switchboard] Disconnected (1200068752.183101233.2571129)

**Comment by c10ud** [comment]
right, would you please open an issue upstream? 

https://bugs.freedesktop.org/enter_bug.cgi?product=papyon

**Comment by EchoUSB** [comment]
I don't really want to create an account etc for a feature I don't really use.

So if someone wants to do it, feel free.

**Comment by sylfel** [comment]
I have the same problem !

Here my log : 

(09:14:28) papyon.transport:<-> Changing gateway to 65.54.49.31:80
(09:14:28) papyon.gnet.HTTP:Received response but wasn't waiting for one
(09:14:29) papyon.transport:<<< 911 0
(09:14:29) papyon.protocol.switchboard:Notification got error :911 0
(09:14:30) papyon.gnet.HTTP:Received error code 400 (Bad Request) from 65.54.61.199:80
(09:14:30) papyon.protocol.switchboard:Disconnected (1265681165)
(09:14:33) papyon.transport:>>> XFR 18 SB
(09:14:33) papyon.transport:<<< XFR 18 SB 65.54.48.70:1863 CKI 1909763449.124139116.24015945 U messenger.msn.com 1
(09:14:33) papyon.protocol.switchboard:New switchboard session 1909763449.124139116.24015945
(09:14:33) papyon.transport:<-> Connecting to gateway.messenger.hotmail.com:80

**Comment by c10ud** [comment]
i reported the issue upstream, we'll see with papyon 0.5.6

**Comment by ammarabdulsalam** [comment]
I have tried to debug this issue
when appearing offline you can chat normally, because it use UUM command, and the request is:
(
UUM 144 xxxxxxxx@hotmail.com 1 1 69
Content-Type: text/plain; charset=utf-8
Dest-Agent: client

message
POST /gateway/gateway.dll?Action=poll&SessionID=516202002.858526562 HTTP/1.0
Content-Length: 0
Accept-Language: en-us
Proxy-Connection: Keep-Alive
Host: 65.54.48.92:80
Accept: _/_
User-Agent: gnet/0.1 (Linux i686)
Connection: Keep-Alive
Pragma: no-cache
Content-Type: application/x-msn-messenger
)
and emesene play sound

but when appearing online the request is:
(
POST /gateway/gateway.dll?Action=poll&SessionID=1513052414.1176094549 HTTP/1.0
Content-Length: 0
Accept-Language: en-us
Proxy-Connection: Keep-Alive
Host: 65.54.50.37:80
Accept: _/_
User-Agent: gnet/0.1 (Linux i686)
Connection: Keep-Alive
Pragma: no-cache
Content-Type: application/x-msn-messenger
)
and emesene doesn't play sound on send.

I hope this can help to fix this issue.

**Comment by c10ud** [comment]
original issue should be fixed now.

try with papyon-0.5.6 (currently unreleased) we will probably make emesene-2.11.8 dependent on that version

**Comment by c10ud** [comment]
ref commit: http://cgit.freedesktop.org/papyon/commit/?id=c437c0a4d2f09ad113e8ab0a7688db1b01c9ba3b
