### ISSUE TITLE
Add contacts to conversation

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#563]
The add contacts to conversation option doesn't work very well. Especially, there are few things that I think should be improved in order to make this tool easier to use:
1-Load time: it takes a very long time to load the tool. It even freezes the program.
2-No connected contacts: they appear earlier than the connected contacts, which doesn't make any sense.
3-Duplicated contacts: the connected contacts appear twice.
4-Adding more than one person: I haven't found the way to add more than one person at the same time to the conversation.

And, apart from that, but related to it, when a contact joins a conversation, there is not any message, so it's hard to know when a contact has been added.

Thanks in advance for doing this excellent program

**Comment by Sbte** [comment]
As for the last part, that's implemented in the latest git master IIRC.

1-3: What options do you use to display your groups in the contact list? Just wondering, because for me it only displays the online contacts. That should probably happen for everyone, but I want a good way to break it at least :P. Also, how many contacts do you have that it takes so long?

4: That's because it uses the same code as the contact list. In the contact list you don't want you be able to select multiple people, because that'd break a lot  of things. I'm not sure if it's easy to fix here.

**Comment by ghost** [comment]
I've got the "Order by group" (Ordenar por grupo in spanish) option selected, and in "Show" (Mostrar), "Show disconnected contacts" (Mostrar contactos desconectados) selected.
I have 237 contacts, so it's normal that to take a lot of time if it also shows disconnected ones.

**Comment by pepeleproso** [comment]
please could you retry? We have improved invite window a bit, and points 1 to 3 should be fixed.

**Comment by ghost** [comment]
Yes, even if it takes a bit to load and I still have some duplicated contacts (due to being at two groups at the same time, so I suppose it's normal and it doesn't matter), the feature has been improved a lot.
Thanks for improving emesene!
