### ISSUE TITLE
Disable auto-reconnect

### ISSUE THREAD

**Issue by jvlppm** [emesene/emesene#589]
I can't use msn at home when i forget emesene opened at work.

When i connect on my msn at home, it disconnects the emesene at work, fine, but after 30 seconds emesene reconnects automatically and disconnects me at home.

How do i disable auto-reconnect?
or disable auto-reconnect if i've connected from another location?

**Comment by Sbte** [comment]
This should happen by default. Clearly a bug

Also, if you login with emesene 2 at both places, nothing should go wrong. You'll stay logged in at both places.

**Comment by c10ud** [comment]
sbte is right, also, in emesene2, reconnecting can be disabled, but since it supports multiple points of presence, just connect the two clients and they'll work same-time

**Comment by Sbte** [comment]
I think it still shouldn't reconnect if it was disconnected from a different location, so why is this closed?

**Comment by c10ud** [comment]
if you choose auto-reconnect, it must do it. different story if you didn't choose it -> bug. which case are we talking about here?

**Comment by Sbte** [comment]
<sbte> c10ud, what do you mean by disabling auto-reconnect
<sbte> where's that possible?
<c10ud> login page
<sbte> that's auto-connect. auto-reconnect is when you get disconnected
<sbte> those are two different things
<sbte> i mean, i don't want to auto-connect, but i do want to auto-reconnect
<sbte> most people do i guess
<sbte> anyway, there's no reason to have an option for that, but it shouldn't do it if it was disconnected from a different location
<sbte> because then you can never login with a different client that doesn't have the feature we have

**Comment by marianoguerra** [comment]
we should not try to reconnect if we get disconnected because someone logged in in other location, because that would generate a loginbattle beteeen the two clients.

I think that was the way on emesene 1, only reconnects on disconnecs from the server not caused by remote login.

**Comment by Sbte** [comment]
This is already implemented. If you have any further problems with the latest version of emesene (2.11.5 or later), please also specify the other client you use. The only thing I can think of is that it doesn't send the right signal....

For reference:

https://github.com/emesene/emesene/blob/master/emesene/e3/papylib/PapyEvents.py#L64
https://github.com/emesene/emesene/blob/master/emesene/emesene.py#L740

**Comment by jvlppm** [comment]
emesene 2 doesn't support proxy, so i can't use it
