### ISSUE TITLE
KeyError... dont know to reproduce

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#625]
[21:06:43 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 1307130677.994842
[21:06:43 WARNING e3.common.Signal] Signal handler (_on_message._on_message) error: 1307130677.994842
Traceback (most recent call last):
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 66, in emit
    if callback(_args, *_kwargs) == False:
  File "/home/andre/emesene/emesene/e3/common/Signal.py", line 114, in __call__
    self.f(self.c(), *arg)
  File "/home/andre/emesene/emesene/gui/gtkui/MessagingMenu.py", line 115, in _on_message
    self._create_indicator("im", Renderers.msnplus_to_plain_text(contact.nick), account, cid=cid)
  File "/home/andre/emesene/emesene/gui/gtkui/MessagingMenu.py", line 180, in _create_indicator
    ind = self.r_indicator_dict[old_cid]
KeyError: 1307130677.994842

**Comment by Sbte** [comment]
Is this with git master of today? I might have fixed this yesterday.

**Comment by zipatei** [comment]
Yes... with commit 6415e4aadeccdfcbaec3

**Comment by Mystro256** [comment]
perhaps papyon related? see https://bugs.freedesktop.org/show_bug.cgi?id=28439

**Comment by c10ud** [comment]
nope, not papyon issue...anyway we could have fixed this already

**Comment by Sbte** [comment]
@c10ud, I think I know why this is happening now. I think this also causes a bug in the UnityLauncher extension.

When we reuse a conversation, we unlink it from the cid. In the MessagingMenu and UnityLauncher, the conversations are linked to the cid however, but once the cid is deleted because the conversation was reused, we get this keyerror in the MessagingMenu and the UnityLauncher leaves the message count there, because the conversation with that cid is never viewed. 

Can we maybe identify conversations by something other than the cid, or maybe use an internal cid for this stuff and a cid that is the same as the papyon cid only for the things that need this?

**Comment by c10ud** [comment]
how about some weird and potential hackish "update_cid" signal that gets fired once the re-use is done so the consumers know they must update their dicts?

**Comment by Sbte** [comment]
I know how to reproduce this now. Just try to open a conversation through the contact list with the user that just said something to you while the message is still unread. The message you receive after that produces the KeyError. Came across this while trying to fix it blindly :P

Fix coming in! :D
