### ISSUE TITLE
We shouldn't be able to start an already started plugin

### ISSUE THREAD

**Issue by arielj** [emesene/emesene#639]
I'm doing a "Hello World" plugin tutorial and found this issue

Now we can start a plugin and then click the start button again and the plugin will be started again (not restarted!)

We have three options:
-We can disable the "start" button on preferences after click (do the oposite with the stop button)
-We can check: if the plugin is started, don't start it again (on plugin manager)
-We can change the "start" button to "restart" button and stop>start the plugin on click

What do you think?

**Comment by c10ud** [comment]
i'd go for the don't start if already started, but ymmv

**Comment by marianoguerra** [comment]
On Wed, Jun 8, 2011 at 6:45 PM, arielj
reply@reply.github.com
wrote:

> I'm doing a "Hello World" plugin tutorial and found this issue
> 
> Now we can start a plugin and then click the start button again and the plugin will be started again (not restarted!)
> 
> We have three options:
> -We can disable the "start" button on preferences after click (do the oposite with the stop button)
> -We can check: if the plugin is started, don't start it again (on plugin manager)
> -We can change the "start" button to "restart" button and stop>start the plugin on click

I think changing the button to stop
and raising an exception on plugin manager if trying to start an
already started plugin

others?

**Comment by Mystro256** [comment]
On a slightly unrelated note, I would also like to add that when a plugin is enabled/executed/started/restarted, the main screen should probably be redrawn or perhaps have the plugins do it, if they need to do so (e.g. Music plugin).

As well, I agree with marianoguerra, as theres no reason to take up space or to have redundant buttons, no?
How's enable/disable sound instead of start/stop by the way? Maybe more user friendly words? Just a thought

**Comment by c10ud** [comment]
@arielj can i cherry pick from your personal branch?

**Comment by arielj** [comment]
yes! I forgot to make the pull request
