### ISSUE TITLE
Non tabbing option

### ISSUE THREAD

**Issue by sigterm** [emesene/emesene#65]
I saw before an issue called option several windows which i can't find anymore.
it gotten closed because of a developer said it's nothing we want in 2010.

However at this moment the tabbing is not practical at resolutions like 1024x768 because the tabs are so big you can only fit like 3 tabs in the conversation window before the arrows start to appear - and that's were it gets annoying.

Remember some users prefer several windows over tabbing, for example me and many of my friends. This is as-well a feature available in emesene 1.x, it would make no sense to not include it in emesene 2. This is not an obsolete feature that does not belong in the 20th century, for example Firefox supports this feature and yes even in 2010.

PS i am not trying to troll or anything =D

**Comment by Mystro256** [comment]
I fully agree, multiple windows can be much more useful for various reasons, especial with Linux's multiple workspaces.

I find having a tabbed window silly because if I have it minimized and someone messages me, I can just click on the minimized window, i have to look through the tabs to see who messaged me. This is even more annoying when two or more people message me at the same time, i don't realize it and people get ignored.

Plus organizing windows around the screen when I'm talking to a lot of people just seems easier to me than using tabs in one window.

**Comment by DragaO** [comment]
i use this feature too - multiple windows.

so, +1 vote for this feature :D

**Comment by Malabarba** [comment]
I don't think it's a priority right now, but it's definitely an important option to have by release date. Using multiple tabs vs multiple windows is entirely a matter of preference and thus should be implemented as an option.

(I use tabs on my small netbook to minimize clutter, but I use windows on my multi-monitor desktop so I can keep an eye on all conversations simultaneously without having to focus them.)

**Comment by Zincr0** [comment]
+1
Plus in the feature, more options, convert a specific tab into a window, leave one tabbed window for each protocol...the sky is the limit :D

**Comment by rosavi** [comment]
I second that! Multiple windows on a tiling WM is a lot more functional than tabs, even more so in a multimonitor setup.

**Comment by Mystro256** [comment]
Perhaps a mixture of the two would be a good idea, sorta like how most web browsers like firefox or chrome work: multiple windows with the ability to have several tabs in any of those windows.

Unfortunately it does seem like something that would be difficult to implement, but could be very useful, allow for more customization, and an interesting option to implement eventually as most programs on Linux, such as nautilus, gedit, firefox, chrome, dolphin, various terminals, etc., have this functionality.

**Comment by edualberice** [comment]
Hello! Now I think I'm commenting the right way here. Sorry guys it's my first time contributing to a project like this hehehe.
Well, as I stated before, for me multiple windows are better then multiple tabs, but as Mystro said above it would be perfect if the two possibilities were implemented because then Greek and Trojan would like it, but I know it's not easy to do it.

**Comment by c10ud** [comment]
thank mariano, kthxbi
