### ISSUE TITLE
Method called on dead object

### ISSUE THREAD

**Issue by oblique** [emesene/emesene#673]
i'm getting this, but i don't know when it's triggered

Traceback (most recent call last):
  File "/usr/share/emesene/e3/common/Signal.py", line 64, in emit
    if callback(_args, *_kwargs) == False:
  File "/usr/share/emesene/e3/common/Signal.py", line 109, in **call**
    raise TypeError('Method called on dead object')
TypeError: Method called on dead object

**Comment by Sbte** [comment]
If you install 2.11.6-devel, there will be a more informative warning instead of this traceback. We are still waiting for this warning to pop up so we can fix this. 

This warning is something we expect to happen in some cases, and there is a garbage collector that fixes any breakage it may cause, but it's still a sign of bad coding style. If emesene was perfect, no one would ever see the warning ;)

So, everyone reading this: Look for a warning containing the message "Method called on dead object".

**Comment by Mystro256** [comment]
I got this warning a lot when working on the music plugin; it seem to happen with the methods on_BLANK_change_succeed, where blank was media, message, etc.

The only instance I can provide right now is:
Seems to happen with either <i>self.session.media_change_succeed(None)</i> or <i>self.profile.personal_message_current_media = self.profile.personal_message, None </i> when called in emesene/e3/papylib/Worker.py Line 1125 and 1126. I believe the error is caused by a child process of the former method mentioned (line 1125) that can't handle a None parameter. Perhaps an <i>if parameter is not None :</i> is necessary in the <i>def media_change_succeed</i> for the line that references <i>on_media_change_succeed</i>

heres the error (yes it happens twice at once):

```
[11:47:02 WARNING e3.common.Signal] Method called on dead object: on_media_change_succeed.on_media_change_succeed
[11:47:02 WARNING e3.common.Signal] Method called on dead object: on_media_change_succeed.on_media_change_succeed
```

**Comment by Sbte** [comment]
Thanks Mystro!

**Comment by Mystro256** [comment]
No problem :)
