### ISSUE TITLE
Integration with Unity

### ISSUE THREAD

**Issue by alexandre596** [emesene/emesene#687]
it's not a issue, it's a "suggestion" and I don't have other placa to write this =/
it would be cool if you put a way to change the stats with unity, to don't need to go to main window, and change over there, and change the icon color, with the stats..

well, it's just a suggestion...

**Comment by Mystro256** [comment]
What do you mean by stats? The display pic and message? And if so, what do you purpose?

If you mean status, this is already done with the me menu on the top right.

**Comment by Sbte** [comment]
Also, I don't think a dropdown menu is possible on the unity launcher. Adding 5 entries that are duplicates of the ones in the memenu is a bit of an overkill I think.

Changing the image is not possible for sure (because you attach the launcher to an icon, not the other way round). The memenu image should already change though.

**Comment by marianoguerra** [comment]
discusses on the list, those features should (and are) be implemented on the me menu

closing
