### ISSUE TITLE
[improvements] Optimize emesene to run properly on multiple instances

### ISSUE THREAD

**Issue by sm-Fifteen** [emesene/emesene#706]
Since I have (like many others) more than one email adress and that my contact list differs heavily between the two, I sometimes have to open both at the same time.
Now, the emesene developpers decided not to optimise emesene to manage multiple accounts. Now, that's fine with me, I understand that they did this for the sake of simplicity, to avoid becoming like pidgin. However, that means that those who do want to have to accounts open at the same time must open emesene twice, and this is a problem because:
1. Auto-connections doesn't check if emesene is running in the first place, and disconnects the first instance
2. Both icons in the tray are exactly the same

What I propose to fix those issues is to have a palette swap or a totally different version of the icon ready, so that if emesene is already running, the new instance could fallback on this instead of reusing the same visual aids.
Also, prevent auto-connect if the target account is already connected on the same computer.

**Comment by c10ud** [comment]
i'm reporting a crazy idea from marianoguerra, if someone who doesn't
read the ML wants to take the job:

imagine we move the main window code to an extension (that is, the
whole content of the window: main menu, userpanel, contact list)

we make an extension called single session that contains a vbox with
the main window extension.

that will give us the current behaviour.

now, supose we create a new extension implementation called "tabbed sessions"

in wich you will have the same main window as now but with a
gtk.Notebook widget containing it and with tabs at the bottom.

the tabs will have the name of the current session and an icon for the
protocol and an extra button with a plus sign.

when you click the plus sign it will create a new tab and put the main
window inside it, when you log in it will put the icon of the protocol
and the account on the tab.

in this way you will have multiple session support in the same window
but without sharing anything (it will be an aggregation of single
protocol instances in a single window in fact)

why? someone will have n sessions opened in a single window instead of
n windows, each protocol doesn't know anything about the others but at
least you have it on a single window.

of course that's the limit, we won't add multiprotocol support anywhere.

just an idea ;)

2011/7/4 Riboshom
reply@reply.github.com:

**Comment by Mystro256** [comment]
Maybe also adding an option for anti-polygamy, along with the tabbed sessions? It seems like a good idea, but I personally would find it much more useful if there was the ability for only one instance of emesene (ie when I click on emesene.desktop, the main window is show rather than opening another window/instance)

Good idea by the way :) but seem like a lot of work haha

**Comment by c10ud** [comment]
i think you can already: emesene -s

2011/7/6 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
Oh didn't know about that, thanks c10ud. Although I do come up with this error when I run it:

```
Another instance of emesene is already running.
org.freedesktop.DBus.Error.ServiceUnknown: The name org.emesene.dbus was not provided by any .service files
```

**Comment by c10ud** [comment]
uhm, then some dbus changed between versions? i don't have that error here :s

**Comment by Mystro256** [comment]
Well I'm using the version straight from the main natty repo :S (1.4.6-1ubuntu6 and python-dbus 0.83.1-1)

Unless it's ibus and/or python-ibus that's causing the issue (both 1.3.9-0ubuntu4~gtk3)

Hmmm... what platform/version are you testing it on? maybe I can figure out

**Comment by c10ud** [comment]
sorry, i remembered it working, but it's as you say.. (the first time
i only ran emesene once) something must have broke it :s

2011/7/7 Mystro256
reply@reply.github.com:

**Comment by Mystro256** [comment]
Oh I see

**Comment by Sbte** [comment]
Time for a regression test! :D

**Comment by Mystro256** [comment]
haha, regressions, they're always fun in a bun ;)

**Comment by c10ud** [comment]
single instance fixed, OP's issue not

**Comment by c10ud** [comment]
> 1. Auto-connections doesn't check if emesene is running in the first place, and disconnects the first instance
>    with msnp18 you can connect multiple instances
> 2. Both icons in the tray are exactly the same
>    different theme for different account should do the trick
