### ISSUE TITLE
Custom emoticons are not migrated by emesene-1-migration tool

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#714]
I used to have a couple of custom emoticons on emesene 1.
When I updated ubuntu and first started emesene 2 it asked if it could migrate my data. After some time in the operation, I noticed my custom emoticons vanished.
Now there's no easy way to re-add them... I need to add one by one, from the .config/emesene1.0 folder.

Any better way to do that?
Any fix for that tool?

**Comment by astagi** [comment]
very strange behavior, for me works... you can retry the synchronization going to preferences -> extensions then you can find the button to synchronize again... let me know...

ah btw, in which folder do you have emesene 1 emoticons??

**Comment by igorsantos07** [comment]
Gonna try it tonight.
BTW, the emesene 1 custom emoticons are in
~/.config/emesene1.0/<<account>>/custom_emoticons.

**Comment by hit** [comment]
I only got most of them migrated, some of them were still missing and I had to add them manually.

**Comment by astagi** [comment]
@hit can you post here their file names?? could help, thanks ^^

**Comment by hit** [comment]
Ok I think I got it. It's the way they are imported. Instead of listing diretory and importing all emoticons _files_, you should just convert "map" to "emoticons.info", because not all emoticon's filenames are in format "shortcut.hash.[gif|png]".

Ex.

Currently IMPORTED:
Shortcut: žombi
Filename: %C5%BEombi.11b41d1f63cba3fd49aa6f166c1ad3abdb37c1e0.gif

Currently NOT imported:
Shortcut: q5
Filename: 2eda58fd9868b73a5ae7662dbfd21b15d2066bfa.png

I guess the file naming in emesene1.x changed in time and since I'm always backing up my emesene conf (at least emoticons) from almost emesene 0.x, there are lots of files using this "old" formatting or smth.
