### ISSUE TITLE
No buttons to hide lateral panel as emesene1 had

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#764]
Emesene 1 used to have a button under each avatar, in the chat window, that would hide the related image.
Emesene 2 doesn't have that; if you want to hide them quickly you need to open menu, options, uncheck the option, and then go there again and check it again.

**Comment by c10ud** [comment]
is that needed for NSFW friends or what? now it's simpler and imho
definitely better

2011/8/7 igorsantos07
reply@reply.github.com:

**Comment by c10ud** [comment]
also, i don't think we can hide only one of the two anymore given how
the widgets are packed

2011/8/8 Riccardo (C10uD) c10ud.dev@gmail.com:

**Comment by igorsantos07** [comment]
Sorry but I don't think it's simpler to open a menu in the contact window and change an option than clicking a button in the chat window (as official live client always did).
And besides, it would change all windows, not only the one I want.
BTW, the official client hides both images too, so I don't think this would be a problem; it just lacks an easy way to hide the avatars from inside the chat window.
I used it also when I needed a little bit more space to read some pasted code, etc. No need to increase window size and then reduce it again, more space was just one click away.

**Comment by Mystro256** [comment]
Well I definitely understand what @igorsantos07 means; a per-window option, just to hide a picture for whatever reason. @c10ud definitely has a point about the widgets though.

I haven't looked at it myself, but perhaps there could be an option to hide both? Maybe a temporary (in the window) and persistent/permanent option (In preferences)?
The former being for those who need to hide the pictures temporary for whatever reason (such as nsfw stuff or what @igorsantos07 said), and the latter for those who want the screen space, don't care about avatars or perhaps find the avatars redundant because the adium theme shows them anyway.

**Comment by c10ud** [comment]
If someone wants to try do something, this is a nice task for newcomers

**Comment by joaojacome** [comment]
Got it working on my fork
https://github.com/joaojacome/emesene

**Comment by Mystro256** [comment]
Then make a pull request :)

**Comment by joaojacome** [comment]
Did it, thanks :D

2011/8/9 Mystro256 <
reply@reply.github.com>

> Then make a pull request :)
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/emesene/emesene/issues/764#issuecomment-1764646

## 

João Jácome
