### ISSUE TITLE
Stored users shown as "myself@hotmail.com|msn"

### ISSUE THREAD

**Issue by igorsantos07** [emesene/emesene#786]
I've pulled from the repos yesterday, and running emesene I noticed that the indicator icon is not being displayed - as I said in another issue.
Turned off my computer after that, just fine. Now I started emesene 2.11.8-dev again and it's showing all the stored users alongside "|msn" in the login box. If I remove that part from the field, it forgets my password and I need to type it again.

Emesene stable (2.11.5) is also behaving the same way.

**Comment by igorsantos07** [comment]
Opened it again and now the user is "igorsantos07@gmail.com|msn|msn" D:

**Comment by Sbte** [comment]
This happened, because you used 2.11.5 and then 2.11.8-devel. Logging in with 2.11.5 reset some of your settings back to the way they were before, which made 2.11.8-devel convert the already converted accounts again. I'll add an additional check for this.

If you use only 2.11.8-devel, you should be fine.

**Comment by Sbte** [comment]
Oh, and your global config is messed up now. You'll have to fix it manually. Just remove any extra |msn or other |protocol.
