### ISSUE TITLE
Global configurations

### ISSUE THREAD

**Issue by pablorodz** [emesene/emesene#796]
hi, 
the only way to configure the application is login first.
This is a good feature, because it makes the app more personalized to the logged user. 
However, i would like to configure the app without being login. One way i see this is having global configurations. When a user is log in, the personal configuration could take the global configuration or override these.

May be someone have a better idea :) 

i don't know if this is the right place for this and i hope someone understand what i'm trying to say (i'm a bit rusty at english)

bye!

**Comment by pablorodz** [comment]
I forgot.
I'm using emesene 2.11.7 in arch linux.

Other thing, i don't know if i'm blind or there is not  even a way to see the "about window" with out loggin in?

**Comment by Sbte** [comment]
Why would you want to do anything in emesene without logging in? What's the point?

**Comment by pablorodz** [comment]
Why wouldn't you?

May be it's not necesary, but some things i can think of is in configuring the proxy (the qt version let you), the tray icon, or just configure the app without an internet connection (while installing a system offline).

It was the first thing i saw and i found odd. It doesn't mean it's wrong, I just wanted to know if there was a reason :)

**Comment by Sbte** [comment]
You can already configure the proxy, but it doesn't really work. Not in the qt version, not in the gtk version. It's a button to the right of the session combo box.

And I have no clue why one would want to install emesene on a system with no internet. And even then, you could just open a dummy session.

The reason is to keep the login window clean and simple. It's also a great way to not have to deal with certain cases where the user is not logged in.

**Comment by pablorodz** [comment]
I really look for the proxy and it was there all the time!

I was't aware of the dummy session. I apologize.

Thanks for the answer!

**Comment by Sbte** [comment]
We'll probably make button look sensitive as soon as it actually works.
