### ISSUE TITLE
can't see when the contact is typing in emesene

### ISSUE THREAD

**Issue by danielgomon** [emesene/emesene#809]
this function works just fine with another client (PIdgin, WLM) but when the contact uses emesene (2.11.5 and 2.11.7) I can't see the gray icon in the tab of the conversation that notifies "your contact is typing"...

**Comment by c10ud** [comment]
because emesene doesn't send the "is typing" notification

**Comment by Mystro256** [comment]
Was this done purposefully or yet to be implemented?

**Comment by danielgomon** [comment]
it would be nice to have this function back in future releases! I think...

**Comment by c10ud** [comment]
we didn't implement because it was mostly useless and required too
many checks in papylib.

as i told sbte today we could implement it as a fake e3.Message (once
the gui spits the right signals) so we re-use the infrastructure in
_handle_action_send_message in papylib (and instruct other backends to
ignore that fake message)

2011/8/28 danielgomon
reply@reply.github.com:
