### ISSUE TITLE
Allow and Blocklist colors

### ISSUE THREAD

**Issue by rockybalboa** [emesene/emesene#823]
In my allow list the all contact is marked with yellow color, but it isn't okay. Any info about this? Is this work normally?

Screenshot: http://noob.hu/2011/09/04/list.png

**Comment by c10ud** [comment]
we just show what the server says, so it's either correct or a wide issue (i remember seeing things like this in the past, so yes they're "normal")

**Comment by rockybalboa** [comment]
I tried it with 3 accounts and the all are the same. Is this work for you?

**Comment by c10ud** [comment]
i have lots of yellow contacts, yes, not all but lots

2011/9/5 rockybalboa
reply@reply.github.com:

**Comment by Sbte** [comment]
It does work for me with one account and not with two others. I really think this is a bug...

**Comment by c10ud** [comment]
just print the memberships of each account to one file and see what
they're saying

2011/9/5 Sbte reply@reply.github.com:

**Comment by arielj** [comment]
We know from emesene1 that msn servers sends us weird lists (it doesn't even work right on the official client, they don't say "this contacts has you" though). I don't think we should rely on the memberships and tell the user "this person has you" "this person don't" knowing that it's bugged server side (it makes people think that WE have the problem...)

Maybe we can add some hint "This is not 100% exact, it dependens on whatever msn server sends us, don't beilive it 100%". We can't fix it since it's not our fault.

**Comment by matiasdelellis** [comment]
Just tell the new msn does not show these lists.

If emesene not removed it, please!, Put this tab in a separate dialog, almost hidden, and with a clear message! ! as above say arielj..

I made tests, and people I'm on their list, in my list are in yellow.

I know people who deleted their contacts for information like this. Primarily from the services on Internet, which are based this.

**Comment by manuargue** [comment]
It's not an emesene bug. The problem is in the server side. I think would be fine if we put a 'caution' label above the list, like arielj says. We can't do anything, because the memberships flags are handled by the server!

**Comment by arielj** [comment]
I'll leave this as "easy" for any new developers that wants to play with preferences.

Just to make it clear, the bug is on the server, excepted fix: Add a label on preferences saying "this is not 100% reliable, it depend's on microsoft's servers" or something like that

**Comment by c10ud** [comment]
agreed
