### ISSUE TITLE
how unistall plugin?

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#825]
How i unistall plugin installed?

**Comment by bubuntux** [comment]
You can remove the plugin from /home/<user>/.config/emesene2/plugins
The gui should do it, this is a bug.

**Comment by Sbte** [comment]
@bubuntux, are you on it? Seems like something small that you can fix ^^

**Comment by bubuntux** [comment]
i'm on another little improvement :P, maybe today send a new pull request, and then i'm going to check this bugs. ;)

**Comment by shuhaowu** [comment]
Is this being fixed? >_> damnit I missed my other chance of doing something simple..

**Comment by bubuntux** [comment]
Go ahead, try to fix this!! i'm working with other little improvements :P

**Comment by shuhaowu** [comment]
This issue seems a little more complicated than I think. I would need to eventually refactor all the code so my "Remove" button would work everywhere regardless of where the button is being used.

(Why does making everything automated, in terms of plugin downloading, seem like a bad idea in the first place, which introduces more.. and really, in my opinion, unnecessary work?)

I'm gonna branch this into an experimental feature in my repo

**Comment by shuhaowu** [comment]
We can tag this with HARD too. >.>

**Comment by Sbte** [comment]
I'll see what I can do.

**Comment by shuhaowu** [comment]
Wait wait! I already have an experiment branch dedicated to this... let me do it :P

**Comment by c10ud** [comment]
commit early push often so we can follow your changes!

**Comment by shuhaowu** [comment]
i'll let sbte do his remove button, personally I'm doing a branch for preference hiding. I want to also introduce YAML files or other config files for meta data for plugins... 

Emesene: https://github.com/ultimatebuster/emesene/tree/for-824
Plugins: https://github.com/ultimatebuster/emesene-supported-plugins/tree/experimental
