### ISSUE TITLE
Feature: Progress bar in unity

### ISSUE THREAD

**Issue by zipatei** [emesene/emesene#882]
Progress bar in unity:

https://static-cdn.addons.mozilla.net/img/uploads/previews/full/57/57432.png?modified=1304446643

**Comment by zipatei** [comment]
More info:

https://wiki.ubuntu.com/Unity/LauncherAPI

**Comment by Sbte** [comment]
What for?

**Comment by zipatei** [comment]
- File Transfer
- Synchronization Progress

**Comment by Sbte** [comment]
Sync is only a once in a lifetime experience, and it's probably not worth the trouble. I don't think anyone will miss it.

File transfer would be a mess, because you can do multiple file transfers at the same time. And it's just eyecandy. If you want to know when it's done, you can just open the conversation window or look for notifications. Not that I recommend using file transfers through MSN to anyone anyway.

Anyhow, this requires a lot of work (as far as I can tell) for just some eyecandy.

**Comment by madjr** [comment]
email count badge would be a nice touch in the future, but right now i think this is low priority

**Comment by Sbte** [comment]
We can't have both unread conversation messages and email messages. That would be extremely confusing.

I'm closing this bug for now, because I don't think this would be a useful addition.
