### ISSUE TITLE
The tray icon of the latest emesene version don' t work

### ISSUE THREAD

**Issue by confuste** [emesene/emesene#888]
I have Ubuntu 11.04, since yesterday ( - the Natty Narwhal - released in April 2011 and supported until October 2012.). The tray icon of the latest emesene version don' t work.

When I press  "X" hides emesene and I can't recover it (though still open and I can hear if someone is online or leaves the session). 

How I can fix the problem? 

Thank you.

**Comment by Sbte** [comment]
It's in the messaging menu (white/blue envelope at the right top of your screen). You can select the Indicator from Preferences->Extensions->tray icon if you don't like it.

**Comment by c10ud** [comment]
The default is "messaging menu" because of the ubuntu policy regarding
instant messengers. You can however use indicators or tray icon just
selecting them from Preference-Extensions.

As for the X, that's the correct behaviour. You bring it back through
the messaging menu. Or, you just make a launcher for emesene with the
-s flag which will keep only one session opened even if you click
multiple times

2011/10/5 varuk
reply@reply.github.com:
