### ISSUE TITLE
music plugin error

### ISSUE THREAD

**Issue by Fabioamd87** [emesene/emesene#959]
I've noticed a things:

after music plugin download it can't permit to open preferences menu, after restart it does.

**Comment by Sbte** [comment]
Ok, what happens is that there is no player when `player = extension.get_instance(CATEGORY)` is called.

This means that the extension is not instantiated. This seems logical, because I can't find any place where those extensions are instantiated, but the weird thing is that the extensions IS instantiated when emesene starts. I have no clue how this happens. If anyone does, then please tell me.

@arielj, @pepeleproso, @marianoguerra

**Comment by Sbte** [comment]
Ah, it's done in the MusicButton pepe just added. Weird place to hide that stuff...

**Comment by Sbte** [comment]
Should be fixed by

https://github.com/emesene/emesene-supported-plugins/commit/0d6d5beca305f649f8996034d3bd1a49b20a69ab
