### ISSUE TITLE
Use notify-osd for notifications

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#963]
I'm not sure in which version the notifications changed, but in latest github version, the notification window it's ugly and it's in a bad position, using notify-osd would be better.
This also could be an extension, much better I think.

**Comment by arielj** [comment]
what notificationGUI extension are you using? maybe you are using
GtkNotification and you should use PyNotification

2011/12/7 Stiveknx <
reply@reply.github.com

**Comment by Stiveknx** [comment]
I don't have another option, only gtk and snarl ....

**Comment by arielj** [comment]
Maybe you have some package missing, check that you have all pynotify
related packaged working on your system.

2011/12/7 Stiveknx <
reply@reply.github.com

**Comment by Stiveknx** [comment]
Yes, I have notify-osd,  libnotify, python-notify also python-pyinotify and I still can't see the option in notificationGUI ...

**Comment by Sbte** [comment]
I see this too. For other applications the notifications look fine. 

I'm not going to work on this though, because in Oneiric, notify-osd is broken for multi-monitor setups (which I have). I had to hack into notify-osd to position them somewhere where I can read them, so I can never know for sure if they work on normal setups.

**Comment by Sbte** [comment]
Select PyNotifitcation from Preferences->Extensions->notificationGUI. I have no idea why the other notifications became the default...

**Comment by Sbte** [comment]
Sorry, I had a messed up git config. Fix coming in a minute.
