### ISSUE TITLE
New microsoft's XMPP interface

### ISSUE THREAD

**Issue by Stiveknx** [emesene/emesene#968]
Microsoft launched a new xmpp interface for messenger, According to them, their intention is "anyone can build innovative messaging clients—either stand-alone or built into their devices—that include access to Messenger’s 300 million active users."

http://windowsteamblog.com/windows_live/b/windowslive/archive/2011/12/14/anyone-can-build-a-windows-live-messenger-client-with-open-standards-access-via-xmpp.aspx

So, I'm wondering, maybe this can add the option to webcam/audio calls in emesene?
Also can fix another things, like bug's when you update stats, or adding contact's...

**Comment by Sbte** [comment]
Actually, as far as I know, it only supports conversations. No groups, no adding contacts, no video, no audio, no custom emoticons, no nothing.

c10ud made a branch though, if you want to try it out:

https://github.com/c10ud/emesene/commits/msn-xmpp

**Comment by c10ud** [comment]
> So, I'm wondering, maybe this can add the option to webcam/audio calls in emesene?

Audio/Video calls are not broken, we just don't have the proprietary codecs required in order to do the call. Everything else at implementation level already works. Unfortunately without codecs you can't do much, as stated many many times.

> Also can fix another things, like bug's when you update stats, or adding contact's...

I never saw such bugs, maybe some server fail when adding contacts but it's not our fault. Also, the xmpp implementation doesn't cover anything but simple text chatting
