### ISSUE TITLE
customize an adium theme

### ISSUE THREAD

**Issue by ghost** [emesene/emesene#978]
hello i have installed this adium theme on my emesene 2.11.11
http://www.adiumxtras.com/index.php?a=xtras&xtra_id=8209

but when i start a conversation at the top it appears a notification all the time and i cannot see the first message
I attach a screenshot to understand what i mean 

http://img843.imageshack.us/img843/7903/screenshotat20120103112.png

Is there any solution about that ? The adium theme has no properties in order to get rid of this notification at the top :(
Also i would not like to change theme , because i already tried a lot of themes(almost all adium themes) and i prefer this one

**Comment by Sbte** [comment]
Remove the Header.html file and you're good.

@pepeleproso, maybe we should disable the headers by default?

**Comment by c10ud** [comment]
@sbte i don't think this is an issue with us but with the theme itself

**Comment by Sbte** [comment]
@c10ud, it happens with every Adium theme with an Header. It's definitely something on our side. Maybe it's fixed with the new Template we have since last week, I'm not sure.

Anyhow, I think those headers (sometimes taking up more than half of the conversation window) don't fit in out conversation window theme, and duplicate what is already there in our own header.

**Comment by pepeleproso** [comment]
normally you can hide header clicking on it. If that isn't the case theme is broken

**Comment by Sbte** [comment]
You have to do that for every conversation? Or only once?

**Comment by pepeleproso** [comment]
for every conversation

**Comment by Sbte** [comment]
So let's remove the header import? Because I don't think there are themes with a header that currently work with emesene...
