### ISSUE TITLE
emesene1.6.3 is lightweight compared with emesene2

### ISSUE THREAD

**Issue by Sacolevas** [emesene/emesene#992]
Hello, 

I use emesene1 and emesene2. I still use emesene1, because of stability and better plugins. And also, because of some features that emesene2 lacks (I have posted a couple of issues to describe some desirable features).

Besides that, I'd like to comment that using Windows and Linux (specifically, Windows 7 and Lubuntu 11.10), I have noticed that emesene2 consumes about 40% more RAM compared with emesene1. Is there something that can be done at this respect? Thanks

**Comment by Sbte** [comment]
This is mostly because we use webkit for rendering the Adium themes. Webkit indeed uses quite some memory, and there is nothing we can do about that. We do provide (less supported) text output, which doesn't use webkit. I think that we import webkit by default though, but text output might be worth a try.

We also have some memory leaks, which are hard to fix, because we are using python. I already spent quite some days fixing leaks, but without much result.

**Comment by c10ud** [comment]
if you're using emesene1 for stability, you're following the wrong path.

that said, more ram is consumed because of a (semi)proper msn library
and webkit. but i feel that's still nothing compared to the amounts
modern (2000+) computers have

2012/1/27 Sacolevas
reply@reply.github.com:
