### ISSUE TITLE
multiple log in in emesene 2.12.1

### ISSUE THREAD

**Issue by pengshao** [emesene/emesene#998]
Hi, I recently noticed that if I log in my hotmail account from an official hotmail messenger, it tells me that I have several emesene log-in on other computers. And this is confirmed that occasionally when my friend sent me a message, several conversation window popped up at the same time ( there was a time 7 windows emerged ). 

Thanks :)

**Comment by Sbte** [comment]
This is most likely because you open emesene multiple times. If you use Ubuntu, it is hiding in the Messaging Menu (grey envelope in the upper right of the screen). In emesene 2.12.2-devel, this won't happen any more. Instead, opening a new instance of emesene will show the instance you already had open.

**Comment by Sbte** [comment]
I just read in the other thread that you use gentoo. Maybe changing the tray icon instance (see Preferences->Extensions->tray icon) can help..

Also, if you only want one instance of emesene open at a time, run emesene through `emesene -s`. This is also what emesene 2.12.2-devel does by default when you click the icon.
